export const SHOW_FORM_PROJECT = 'SHOW_FORM_PROJECT';
export const GET_PROJECTS = 'GET_PROJECTS';
export const SET_PROJECT = 'SET_PROJECT';
export const GET_CURRENT_PROJECT = 'GET_CURRENT_PROJECT';
export const DELETE_PROJECT = 'DELETE_PROJECT';


export const GET_TASKS_BY_PROJECTID = 'GET_TASKS_BY_PROJECTID';
export const SET_TASK_BY_PROJECT = 'SET_TASK_BY_PROJECT';